meta-bletchley: motor-ctrl: clean up SYSTEMD variables
motor-ctrl recipe was reported to periodically fail with:

    ERROR: When reparsing motor-ctrl_0.1.bb:do_fetch, the basehash value
    changed from AAA to BBB. The metadata is not deterministic and this
    needs to be fixed.

There was inconsistencies in the way the SYSTEMD services were defined
and some of them appeared to not instantiate templates correctly.
Clean them all up to match.

Also perform trivial alphabetic sorting of some other variables.

Signed-off-by: Patrick Williams <patrick@stwcx.xyz>
Change-Id: I9c66fa1106a4003041f39c68c1a43ef8b6a2c00e