treewide: handle upstream TEMPLATECONF move
The latest poky commit is requiring us to have all of
our template configs in a subdirectory instead of directly in
the `conf` directory.  Without this we end up with errors during
setup like:

```
Error: TEMPLATECONF value (which is .../openbmc/meta-facebook/meta-bletchley/conf) must point to meta-some-layer/conf/templates/template-name
```

Fix this by moving all of our template files into the 'default'
template subdirectory (following the pattern of poky) and modifying
`setup` as necessary to follow.

Signed-off-by: Patrick Williams <patrick@stwcx.xyz>
Change-Id: Iecefde73d55acbb6bc63ae3d68c4311adaf327ae