emmc: fix ast2600-emmc target machine build failed
root cause:
mkfs.ext4 does not support "--pad=${RWFS_SIZE}" option

```
mkfs.ext4: invalid option -- '-'
| Usage: mkfs.ext4 [-c|-l filename] [-b block-size] [-C cluster-size]
| [-i bytes-per-inode] [-I inode-size] [-J journal-options]
| [-G flex-group-size] [-N number-of-inodes] [-d root-directory]
| [-m reserved-blocks-percentage] [-o creator-os]
| [-g blocks-per-group] [-L volume-label] [-M last-mounted-directory]
| [-O feature[,...]] [-r fs-revision] [-E extended-option[,...]]
| [-t fs-type] [-T usage-type ] [-U UUID] [-e errors_behavior][-z undo_file]
| [-jnqvDFSV] device [blocks-count]
| WARNING: run.do_generate_rwfs_ext4.12317:173 exit 1 from '$cmd $opts'
| WARNING: Backtrace (BB generated script):
| #1: make_rwfs, run.do_generate_rwfs_ext4.12317, line 173
| #2: do_generate_rwfs_ext4, run.do_generate_rwfs_ext4.12317, line 150
| #3: main, run.do_generate_rwfs_ext4.12317, line 185
NOTE: recipe obmc-phosphor-image-1.0-r0: task do_generate_rwfs_ext4: Failed
ERROR: Task (obmc-phosphor-image.bb:do_generate_rwfs_ext4) failed with exit code '1'
```

Solution:
remove "--pad=${RWFS_SIZE}" from "static-rwfs-jffs2" DISTROOVERRIDES

Signed-off-by: Jamin Lin <jamin_lin@aspeedtech.com>
Change-Id: Ieb383a6b611c7541b2698b0d7799ee69436d368d