Fix the compilation error when building aspeed-image-sdk for AST2500
Fix the following compilation error:

ERROR: Nothing RPROVIDES 'packagegroup-aspeed-apps' (but /home/slee/aspeed/openbmc-0320/openbmc/../meta-aspeed-sdk/recipes-aspeed/images/aspeed-image-initramfs.bb RDEPENDS on or otherwise requires it)
packagegroup-aspeed RPROVIDES packagegroup-aspeed-apps but was skipped: PREFERRED_PROVIDER_virtual/obmc-system-mgmt set to packagegroup-aspeed-system, not packagegroup-aspeed
NOTE: Runtime target 'packagegroup-aspeed-apps' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-aspeed-apps']
ERROR: Required build target 'aspeed-image-sdk' has no buildable providers.
Missing or unbuildable dependency chain was: ['aspeed-image-sdk', 'virtual/kernel', 'aspeed-image-initramfs', 'packagegroup-aspeed-apps']


Signed-off-by: Steven Lee <steven_lee@aspeedtech.com>
Change-Id: I69ce35d1da80c3d0261b99085d43539e9ac343b4