phosphor-misc: Fix Nothing RPROVIDES 'phosphor-misc' issue
build the image with phosphor-misc will report below error:
ERROR: Required build target 'obmc-phosphor-image'
       has no buildable providers.Missing or unbuildable
       dependency chain was: ['obmc-phosphor-image',
       'packagegroup-obmc-apps-extras',
       'phosphor-misc-usb-ctrl', 'phosphor-misc']

Tested:
build the image with phosphor-misc pass.

Signed-off-by: Wang Xiaohua <wangxiaohua.1217@bytedance.com>
Signed-off-by: Patrick Williams <patrick@stwcx.xyz>
Change-Id: I2f74fbb109f108fd970a514b25092a509ed75b43