meta-openpower: pdbg: switch SRCREV to git hash
Latest Yocto upstream seems to prefer SRCREV to be a git-hash over a tag
name.  I cannot find any recipes in the poky tree that leave SRCREV as a
tag even when the recipe is not a `_git.bb`.  When attempting to do a
subtree update we are observing the following failure:

    ERROR: pdbg-3.4-r0 do_fetch: Bitbake Fetcher Error:
    FetchError("Recipe uses a floating tag/branch without a fixed
    SRCREV yet doesn't call bb.fetch2.get_srcrev() (use SRCPV in PV
    for OE).", None)

Switch pdbg to use the git hash of the 3.4 tag as the SRCREV instead of
the generic "v3.4" tag name.

Signed-off-by: Patrick Williams <patrick@stwcx.xyz>
Change-Id: Ifdef91253c4b62003e19945a934094f8edd968d9